spring:
  datasource:
    url: jdbc:h2:file:/home/guilheme/banco
    driverClassName: org.h2.Driver
    username: guilherme
    password: 1234
  h2:
    console:
      enabled: true
    path: /h2
jpa:
  show-sql: true
